config/routes.rb
Rails.application.routes.draw do
  get 'useres/index'

  resources :contas
  resources :fornecedores
  resources :categorias
  resources :modalidades
  resources :vendedores

  get '/produtos/rel_estoque' => 'produtos#rel_estoque', :as => :produtos_rel_estoque
  
  devise_for :useres

  match '/users',   to: 'users#index',   via: 'get'

  get 'welcome/index'
  root 'welcome#index'

  resources :prodentradas
  resources :entradas
  resources :recebimentos
  resources :vendas
  resources :produtos
  resources :pedidos
  resources :clientes

end

app/models/recebimento.rb
class Recebimento < ActiveRecord::Base
  belongs_to :pedido
  has_one :cliente, through: :pedido

  validates :vencimento, :valor, presence: true
  validates :valor, numericality: true

  validate :valida_pedido_id, on: :create



  def valida_pedido_id
    if self.pedido_id.blank?
      errors.add(:pedido_id, "Pelo menos um pedido é requerido!") 
    end
  end
 
  def self.search(search)
  	if search == "abertos"
		Recebimento.where(pagamento: [nil, ''])
	else
		if search == "recebidos"
			Recebimento.where("pagamento != ''")
		else
			Recebimento.order(:vencimento)
		end
	end
  end

  def self.buscacliente(buscacliente)
  	Recebimento.joins(:cliente).where("clientes.nome ILIKE ?", "%#{buscacliente}%")
  end
end

app/controllers/recebimentos_controller.rb
class RecebimentosController < ApplicationController
  before_action :set_recebimento, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /recebimentos
  # GET /recebimentos.json
  def index
    @recebimentos = Recebimento.order(:vencimento).page(params['page']).per(5)
    if params[:search] != ""
      @recebimentos = Recebimento.search(params[:search]).page(params['page']).per(5)
    else
      if params[:buscacliente] != ""
        @recebimentos = Recebimento.buscacliente(params[:buscacliente]).page(params['page']).per(5)
      else
        @recebimentos = Recebimento.order(:vencimento).page(params['page']).per(5)
      end
    end
  end

  # GET /recebimentos/1
  # GET /recebimentos/1.json
  def show
  end

  # GET /recebimentos/new
  def new
    @recebimento = Recebimento.new
  end

  # GET /recebimentos/1/edit
  def edit
  end

  # POST /recebimentos
  # POST /recebimentos.json
  def create
    @recebimento = Recebimento.new(recebimento_params)

    respond_to do |format|
      if @recebimento.save
        format.html { redirect_to @recebimento, notice: t('.sucesso') }
        format.json { render :show, status: :created, location: @recebimento }
      else
        format.html { render :new }
        format.json { render json: @recebimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recebimentos/1
  # PATCH/PUT /recebimentos/1.json
  def update
    respond_to do |format|
      if @recebimento.update(recebimento_params)
        format.html { redirect_to @recebimento, notice: t('.atualizado') }
        format.json { render :show, status: :ok, location: @recebimento }
      else
        format.html { render :edit }
        format.json { render json: @recebimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recebimentos/1
  # DELETE /recebimentos/1.json
  def destroy
    @recebimento.destroy
    respond_to do |format|
      format.html { redirect_to recebimentos_url, notice: t('.apagado') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recebimento
      @recebimento = Recebimento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recebimento_params
      params.require(:recebimento).permit(:pedido_id, :vencimento, :pagamento, :valor)
    end
end

app/helpers/recebimentos_helper.rb
module RecebimentosHelper
end

app/views/recebimentos/_form.html.erb
<%= form_for @recebimento, :html => { :class => "form-horizontal recebimento" } do |f| %>

  <% if @recebimento.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@recebimento.errors.count, "error") %> prohibited this recebimento from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @recebimento.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :pedido_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.collection_select(:pedido_id, Pedido.all, :id, :id, {prompt: "Selecione o pedido"}, {class: "form-control"}) %>
    </div>
    <%=f.error_span(:pedido_id) %>
  </div>
  <div class="form-group">
    <%= f.label :vencimento, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :vencimento, placeholder: "yyyy-mm-dd", :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:vencimento) %>
  </div>
  <div class="form-group">
    <%= f.label :pagamento, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :pagamento, placeholder: "yyyy-mm-dd", :class => 'form-control' %>
    </div>
    <%=f.error_span(:pagamento) %>
  </div>
  <div class="form-group">
    <%= f.label :valor, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :valor, placeholder: "R$ ", :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:valor) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                recebimentos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>


<script type="text/javascript">
  $('#recebimento_vencimento').datepicker({format: 'yyyy-mm-dd', language: 'pt-BR'})
  $('#recebimento_pagamento').datepicker({format: 'yyyy-mm-dd', language: 'pt-BR'})  
</script>

app/views/recebimentos/_formprincipalr.html.erb
<%= form_for @recebimento, :html => { :class => "form-horizontal recebimento" } do |f| %>

  <% if @recebimento.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@recebimento.errors.count, "error") %> prohibited this recebimento from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @recebimento.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :pedido_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.collection_select(:pedido_id, Pedido.all, :id, :id, {prompt: "Selecione o pedido"}, {class: "form-control", :disabled => true}) %>
    </div>
    <%=f.error_span(:pedido_id) %>
  </div>
  <div class="form-group">
    <%= f.label :vencimento, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :vencimento, :class => 'form-control' %>
    </div>
    <%=f.error_span(:vencimento) %>
  </div>
  <div class="form-group">
    <%= f.label :pagamento, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :pagamento, :class => 'form-control' %>
    </div>
    <%=f.error_span(:pagamento) %>
  </div>
  <div class="form-group">
    <%= f.label :valor, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :valor, :class => 'form-control' %>
    </div>
    <%=f.error_span(:valor) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                recebimentos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>


<script type="text/javascript">
  $('#recebimento_vencimento').datepicker({format: 'yyyy-mm-dd', language: 'pt-BR'})
  $('#recebimento_pagamento').datepicker({format: 'yyyy-mm-dd', language: 'pt-BR'})  
</script>

app/views/recebimentos/edit.html.erb
<%- model_class = Recebimento -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'formprincipalr' %>

app/views/recebimentos/index.html.erb
<%- model_class = Recebimento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= form_tag(recebimentos_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: " abertos / recebidos" %>
  <%= submit_tag "Buscar" %>
  &nbsp;
  &nbsp;
  &nbsp;
  <%= text_field_tag :buscacliente, params[:buscacliente], placeholder: " Nome cliente" %>
  <%= submit_tag "Buscar por nome" %>
<% end %>
<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:pedido_id) %></th>
      <th><%= model_class.human_attribute_name(:cliente) %></th>
      <th><%= model_class.human_attribute_name(:vencimento) %></th>
      <th><%= model_class.human_attribute_name(:pagamento) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @recebimentos.each do |recebimento| %>
      <tr>
        <td><%= link_to recebimento.id, recebimento_path(recebimento) %></td>
        <td><%= recebimento.pedido_id %></td>
        <td><%= recebimento.pedido.cliente.nome %></td>
        <td><%= formatadata(recebimento.vencimento) %></td>
        <td><%= formatadata(recebimento.pagamento) %></td>
        <td><%= number_to_currency(recebimento.valor, unit: "R$", separator: ",", delimiter: ".") %></td>
        <td><%=l recebimento.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_recebimento_path(recebimento), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      recebimento_path(recebimento),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<b>Valor Total: <%= number_to_currency(@recebimentos.sum(:valor), unit: "R$", separator: ",", delimiter: ".") %></b>
<br>
<br>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_recebimento_path,
            :class => 'btn btn-primary' %>
<br>
<br>
<%= paginate @recebimentos %>

app/views/recebimentos/new.html.erb
<%- model_class = Recebimento -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/recebimentos/show.html.erb
<%- model_class = Recebimento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:pedido_id) %>:</strong></dt>
  <dd><%= @recebimento.pedido_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vencimento) %>:</strong></dt>
  <dd><%= @recebimento.vencimento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pagamento) %>:</strong></dt>
  <dd><%= @recebimento.pagamento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:valor) %>:</strong></dt>
  <dd><%= number_to_currency(@recebimento.valor, unit: "R$", separator: ",", delimiter: ".") %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              recebimentos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_recebimento_path(@recebimento), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              recebimento_path(@recebimento),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>