config/routes.rb
Rails.application.routes.draw do
  get 'useres/index'

  resources :contas
  resources :fornecedores
  resources :categorias
  resources :modalidades
  resources :vendedores

  get '/produtos/rel_estoque' => 'produtos#rel_estoque', :as => :produtos_rel_estoque
  
  devise_for :useres

  match '/users',   to: 'users#index',   via: 'get'

  get 'welcome/index'
  root 'welcome#index'

  resources :prodentradas
  resources :entradas
  resources :recebimentos
  resources :vendas
  resources :produtos
  resources :pedidos
  resources :clientes

end

app/models/modalidade.rb
class Modalidade < ActiveRecord::Base
	has_many :vendas
end

app/controllers/modalidades_controller.rb
class ModalidadesController < ApplicationController
  before_action :set_modalidade, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /modalidades
  # GET /modalidades.json
  def index
    @modalidades = Modalidade.all
  end

  # GET /modalidades/1
  # GET /modalidades/1.json
  def show
  end

  # GET /modalidades/new
  def new
    @modalidade = Modalidade.new
  end

  # GET /modalidades/1/edit
  def edit
  end

  # POST /modalidades
  # POST /modalidades.json
  def create
    @modalidade = Modalidade.new(modalidade_params)

    respond_to do |format|
      if @modalidade.save
        format.html { redirect_to @modalidade, notice: t('.sucesso') }
        format.json { render :show, status: :created, location: @modalidade }
      else
        format.html { render :new }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modalidades/1
  # PATCH/PUT /modalidades/1.json
  def update
    respond_to do |format|
      if @modalidade.update(modalidade_params)
        format.html { redirect_to @modalidade, notice: t('.atualizado') }
        format.json { render :show, status: :ok, location: @modalidade }
      else
        format.html { render :edit }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modalidades/1
  # DELETE /modalidades/1.json
  def destroy
    @modalidade.destroy
    respond_to do |format|
      format.html { redirect_to modalidades_url, notice: t('.apagado') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modalidade
      @modalidade = Modalidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def modalidade_params
      params.require(:modalidade).permit(:nome, :valor)
    end
end

app/helpers/modalidades_helper.rb
module ModalidadesHelper
end

app/views/modalidades/_form.html.erb
<%= form_for @modalidade, :html => { :class => "form-horizontal modalidade" } do |f| %>

  <% if @modalidade.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@modalidade.errors.count, "error") %> prohibited this modalidade from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @modalidade.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :valor, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :valor, :class => 'form-control' %>
    </div>
    <%=f.error_span(:valor) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                modalidades_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/modalidades/edit.html.erb
<%- model_class = Modalidade -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/modalidades/index.html.erb
<%- model_class = Modalidade -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @modalidades.each do |modalidade| %>
      <tr>
        <td><%= link_to modalidade.id, modalidade_path(modalidade) %></td>
        <td><%= modalidade.nome %></td>
        <td><%= modalidade.valor %></td>
        <td><%=l modalidade.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_modalidade_path(modalidade), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      modalidade_path(modalidade),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_modalidade_path,
            :class => 'btn btn-primary', :style => "display: none" %>

app/views/modalidades/new.html.erb
<%- model_class = Modalidade -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/modalidades/show.html.erb
<%- model_class = Modalidade -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @modalidade.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:valor) %>:</strong></dt>
  <dd><%= @modalidade.valor %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              modalidades_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_modalidade_path(@modalidade), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              modalidade_path(@modalidade),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>