config/routes.rb
Rails.application.routes.draw do
  get 'useres/index'

  resources :contas
  resources :fornecedores
  resources :categorias
  resources :modalidades
  resources :vendedores

  get '/produtos/rel_estoque' => 'produtos#rel_estoque', :as => :produtos_rel_estoque
  
  devise_for :useres

  match '/users',   to: 'users#index',   via: 'get'

  get 'welcome/index'
  root 'welcome#index'

  resources :prodentradas
  resources :entradas
  resources :recebimentos
  resources :vendas
  resources :produtos
  resources :pedidos
  resources :clientes

end

app/models/produto.rb
class Produto < ActiveRecord::Base
	has_many :vendas, dependent: :restrict_with_error
	has_many :produtos, through: :vendas
	has_many :prodentradas, dependent: :restrict_with_error
	has_many :entradas, through: :prodentradas
	belongs_to :categoria

	validates :nome, presence: true
	validates :estoque, numericality: { only_integer: true }
	validates :precovenda, :precocompra, numericality: true

	def self.search(search)
		where("nome ILIKE ?", "%#{search}%") 
	end

	def nome_preco
    	"#{nome} -- R$ #{precovenda}"
  	end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.order(:nome).page(params['page']).per(5)
    if params[:search] != ""
      @produtos = Produto.search(params[:search]).page(params['page']).per(5)
    else
      @produtos = Produto.order(:nome).page(params['page']).per(5)
    end
  end

  def rel_estoque
    @produtos = Produto.order(:nome)
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ProdutoPdf.new(@produtos, view_context)
        send_data pdf.render, 
                  filename: "produto_.pdf",
                  type: "application/pdf",
                  disposition: "inline"
      end
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: t('.sucesso') }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: t('.atualizado') }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      if @produto.vendas.size > 0 || @produto.prodentradas.size > 0
        format.html { redirect_to produtos_url, danger: 'Imposivel excluir este produto.' }
        format.json { head :no_content }
      else
        format.html { redirect_to produtos_url, notice: t('.apagado') }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:categoria_id, :nome, :descricao, :precocompra, :precovenda, :estoque)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_editproduto.html.erb
<%= form_for @produto, :html => { :class => "form-horizontal produto" } do |f| %>

  <% if @produto.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @produto.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>

  <div class="form-group">
    <%= f.label :categoria_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
      <%= f.collection_select(:categoria_id, Categoria.all, :id, :nome, {prompt: "Selecione a categoria"}, {class: "form-control"})%>
    </div>
    <%=f.error_span(:categoria_id) %>
  </div>
  
  <div class="form-group">
    <%= f.label :descricao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :descricao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:descricao) %>
  </div>
  <div class="form-group">
    <%= f.label :precocompra, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :precocompra, :class => 'form-control' %>
    </div>
    <%=f.error_span(:precocompra) %>
  </div>
  <div class="form-group">
    <%= f.label :precovenda, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :precovenda, :class => 'form-control' %>
    </div>
    <%=f.error_span(:precovenda) %>
  </div>
  <div class="form-group">
    <%= f.label :estoque, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :estoque, :class => 'form-control', :disabled => true %>
    </div>
    <%=f.error_span(:estoque) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                produtos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/produtos/_form.html.erb
<%= form_for @produto, :html => { :class => "form-horizontal produto" } do |f| %>

  <% if @produto.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @produto.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:nome) %>
  </div>

  <div class="form-group">
    <%= f.label :categoria_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
      <%= f.collection_select(:categoria_id, Categoria.all, :id, :nome, {prompt: "Selecione a categoria"}, {class: "form-control"})%>
    </div>
    <%=f.error_span(:categoria_id) %>
  </div>

  <div class="form-group">
    <%= f.label :descricao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :descricao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:descricao) %>
  </div>
  <div class="form-group">
    <%= f.label :precocompra, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :precocompra, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:precocompra) %>
  </div>
  <div class="form-group">
    <%= f.label :precovenda, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :precovenda, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:precovenda) %>
  </div>
  <div class="form-group">
    <%= f.label :estoque, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :estoque, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:estoque) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                produtos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/produtos/edit.html.erb
<%- model_class = Produto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'editproduto' %>

app/views/produtos/index.html.erb
<%- model_class = Produto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>

  <%= link_to produtos_rel_estoque_path(@produtos, format: "pdf") do %>
    <i class="glyphicon glyphicon-print"></i> Relatório em PDF
  <% end %>
</div>

<%= form_tag(produtos_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: " Buscar Produto" %>
  <%= submit_tag "Buscar" %>
<% end %>
<br>


<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%= model_class.human_attribute_name(:precocompra) %></th>
      <th><%= model_class.human_attribute_name(:precovenda) %></th>
      <th><%= model_class.human_attribute_name(:estoque) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= link_to produto.id, produto_path(produto) %></td>
        <td><%= produto.nome %></td>
        <td><%= produto.descricao %></td>
        <td><%= number_to_currency(produto.precocompra, unit: "R$", separator: ",", delimiter: "") %></td>
        <td><%= number_to_currency(produto.precovenda, unit: "R$", separator: ",", delimiter: "") %></td>
        <td><%= produto.estoque %></td>
        <td><%=l produto.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_produto_path(produto), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      produto_path(produto),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_produto_path,
            :class => 'btn btn-primary' %>

<br>
<br>
<%= paginate @produtos %>

app/views/produtos/new.html.erb
<%- model_class = Produto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/produtos/show.html.erb
<%- model_class = Produto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @produto.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%= @produto.descricao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:precocompra) %>:</strong></dt>
  <dd><%= number_to_currency(@produto.precocompra, unit: "R$", separator: ",", delimiter: "") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:precovenda) %>:</strong></dt>
  <dd><%= number_to_currency(@produto.precovenda, unit: "R$", separator: ",", delimiter: "") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:estoque) %>:</strong></dt>
  <dd><%= @produto.estoque %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              produtos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_produto_path(@produto), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              produto_path(@produto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>